name: end-to-end

on:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    name: Run Cypress tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - run: npm install --save-dev cypress
      - name: Cypress run
        uses: cypress-io/github-action@v2
