name: PHP/Assets Lint

on: [push, pull_request]

jobs:
  lint-php:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer lint
    - name: Check against phpcs.xml.dist
      run: composer checkcs

  lint-assets:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.13.0
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.0
    - run: npm ci
    - run: npm run lint:scss --silent
    - run: npm run lint:js --silent
    - run: npm run build
