name: Uptime

on:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://www.ocaduillustration.com/"
        expected-statuses: "200,301"
