# This is a basic workflow to help you get started with Actions

name: Uptime

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://www.ocaduillustration.com/"
        expected-statuses: "200,301"
