name: Uptime

on:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  ping-site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      uses: srt32/uptime@v0.2.1
      with:
        url-to-hit: "https://www.ocaduillustration.com/"
        expected-statuses: "200,301"
  e2e:
    needs: ping-site
    runs-on: ubuntu-latest
    name: Run Cypress tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - run: npm install --save-dev cypress
      - name: Cypress run
        uses: cypress-io/github-action@v2
